CREATE DATABASE QLAP

USE QLAP

CREATE TABLE TACGIA(
	MATG CHAR(5) CONSTRAINT TACGIA_MATG_PK PRIMARY KEY,
	TENTG VARCHAR(20),
	NGSINH SMALLDATETIME,
	SDT VARCHAR(15),
	GIOITINH CHAR(5),
	SOTACPHAM INT
)

CREATE TABLE TACPHAM(
	MATP CHAR(5) CONSTRAINT TACPHAM_MATP_PK PRIMARY KEY,
	TENTP VARCHAR(25),
	SOTRANG INT,
	THELOAI VARCHAR(25),
	MATG CHAR(5)
)


CREATE TABLE HDXUATBAN(
	MAHD CHAR(5) CONSTRAINT HDXUATBAN_MAHD_PK PRIMARY KEY,
	MATG CHAR(5),
	NGAYKY SMALLDATETIME,
	TILE NUMERIC(4,2),
	TONGCHIPHI INT
)

CREATE TABLE CTXB(
	MAHD CHAR(5),
	MATP CHAR(5),
	SOBANIN INT,
	SOTIEN MONEY,
	CHATLIEU VARCHAR(25)
)

ALTER TABLE TACPHAM ADD
		CONSTRAINT TACPHAM_MATG_FK FOREIGN KEY(MATG)
				REFERENCES TACGIA(MATG)

ALTER TABLE HDXUATBAN ADD
		CONSTRAINT HDXUATBAN_MATG_FK FOREIGN KEY(MATG)
				REFERENCES TACGIA(MATG)

ALTER TABLE CTXB ADD
		CONSTRAINT CTXH_MAHD_FK FOREIGN KEY(MAHD)
				REFERENCES HDXUATBAN(MAHD)

ALTER TABLE CTXB ADD
		CONSTRAINT CTXB_MATP_FK FOREIGN KEY(MATP)
				REFERENCES TACPHAM(MATP)

/*Phần II*/
/*Câu 1*/

SELECT *
FROM TACPHAM, TACGIA  
WHERE TACPHAM.MATG = TACGIA.MATG AND TENTG = 'Lương Tường Quy'

/*Câu 2*/
SELECT TACGIA.MATG, SUM(TONGCHIPHI)
FROM TACGIA, HDXUATBAN
WHERE TACGIA.MATG = HDXUATBAN.MATG AND MONTH(NGAYKY) = 12 AND YEAR(NGAYKY) = 2020
GROUP BY TACGIA.MATG
HAVING SUM(TONGCHIPHI) > 100000000

/*Câu 3*/
SELECT TACPHAM.MATP 
FROM TACPHAM, HDXUATBAN 
WHERE TACPHAM.MATG = HDXUATBAN.MATG AND (TILE > 0.8 AND MONTH(NGAYKY) = 11 AND YEAR(NGAYKY) = 2020)
OR (TILE < 0.8 AND MONTH(NGAYKY) = 5 AND YEAR(NGAYKY) = 2020)

/*Câu 4*/
SELECT MAHD 
FROM HDXUATBAN 
WHERE NOT EXISTS (
		SELECT *
		FROM TACGIA, HDXUATBAN, TACPHAM 
		WHERE TACGIA.MATG = HDXUATBAN.MATG AND TACPHAM.MATG = TACGIA.MATG AND
		TENTG = 'Phò Khánh Hưng' AND THELOAI = 'Trinh thám' AND NOT EXISTS(
				SELECT *
				FROM CTXB
				WHERE CTXB.MAHD = HDXUATBAN.MAHD AND CTXB.MATP = TACPHAM.MATP 
				AND TACPHAM.MATG = TACGIA.MATG AND YEAR(NGAYKY) = 2020
		)
)

/*Câu 5*/
SELECT TACGIA.MATG
FROM TACGIA, HDXUATBAN, CTXB  
WHERE TACGIA.MATG = HDXUATBAN.MATG AND HDXUATBAN.MAHD = CTXB.MAHD 
GROUP BY TACGIA.MATG 
HAVING SUM(SOBANIN) >= ALL (
		SELECT SUM(SOBANIN)
		FROM TACGIA, HDXUATBAN, CTXB
		WHERE TACGIA.MATG = HDXUATBAN.MATG AND HDXUATBAN.MAHD = CTXB.MAHD 
		GROUP BY TACGIA.MATG
) AND SUM(TONGCHIPHI) >= ALL (
		SELECT SUM(TONGCHIPHI)
		FROM TACGIA, HDXUATBAN 
		WHERE TACGIA.MATG = HDXUATBAN.MATG 
		GROUP BY TACGIA.MATG
)

/*Phần III*/
ALTER TABLE TACPHAM ADD
		CONSTRAINT TACPHAM_THELOAI_SOTRANG
				CHECK ((THELOAI = 'Trinh thám' AND SOTRANG > 100) OR (THELOAI <> 'Trinh thám'))

/*Phần IV*/
GO
CREATE TRIGGER THEMSUA_CTXB ON CTXB
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAHD CHAR(5), @SOBANIN INT, @SOTIEN MONEY, @TONGCHIPHI MONEY
	SELECT @MAHD = MAHD, @SOBANIN = SOBANIN, @SOTIEN = SOTIEN 
	FROM INSERTED 

	SELECT @TONGCHIPHI = TONGCHIPHI 
	FROM HDXUATBAN
	WHERE MAHD = @MAHD 

	IF (@SOBANIN * @SOTIEN <> @TONGCHIPHI)
	BEGIN
			PRINT 'SO BAN IN VA SO TIEN KHONG HOP LE!'
			ROLLBACK TRANSACTION
	END
	ELSE BEGIN
			PRINT 'THEM CTXB THANH CONG!'
	END
END