CREATE DATABASE DE1

USE DE1

CREATE TABLE TACGIA (
	MaTG CHAR(5) CONSTRAINT TACGIA_MaTG_PK PRIMARY KEY(MaTG),
	HoTen VARCHAR(20),
	DiaChi VARCHAR(50),
	NgSinh SMALLDATETIME,
	SoDT VARCHAR(15)
)

CREATE TABLE SACH (
	MaSach CHAR(5) CONSTRAINT SACH_MaSach_PK PRIMARY KEY(MaSach),
	TenSach VARCHAR(25),
	TheLoai VARCHAR(25)
)

CREATE TABLE TACGIA_SACH (
	MaTG CHAR(5),
	MaSach CHAR(5),
	CONSTRAINT TACGIA_SACH_MaTG_MaSach_PK PRIMARY KEY(MaTG, MaSach),
	CONSTRAINT TACGIA_SACH_MaTG_FK FOREIGN KEY (MaTG)
			REFERENCES TACGIA(MaTG),
	CONSTRAINT TACGIA_SACH_MaSach_FK FOREIGN KEY(MaSach)
			REFERENCES SACH(MaSach)
)

CREATE TABLE PHATHANH (
	MaPH CHAR(5) CONSTRAINT PHATHANH_MaPH_PK PRIMARY KEY(MaPH),
	MaSach CHAR(5) CONSTRAINT PHATHANH_MaSach_FK FOREIGN KEY(MaSach)
						REFERENCES SACH(MaSach),
	NgayPH SMALLDATETIME,
	SoLuong INT,
	NhaXuatBan VARCHAR(20)
)