CREATE DATABASE QLKS

USE QLKS 

CREATE TABLE KHU (
	MaKhu CHAR(4) CONSTRAINT KHU_MaKhu_PK PRIMARY KEY,
	TenKhu VARCHAR(40),
	Tang VARCHAR(20),
	TruongKhu VARCHAR(40)
)

CREATE TABLE NHANVIEN(
	MaNV CHAR(10) CONSTRAINT NHANVIEN_MaNV_PK PRIMARY KEY,
	TenNV VARCHAR(40),
	NgaySinh SMALLDATETIME,
	Sodienthoai VARCHAR(20)
)

CREATE TABLE TRUC(
	Macatruc CHAR(10),
	MaNV CHAR(10),
	ThoiGianBatDau SMALLDATETIME,
	ThoiGianKetThuc SMALLDATETIME,
	CONSTRAINT TRUC_Macatruc_MaNV_PK PRIMARY KEY(Macatruc, MaNV)
)

DROP TABLE NHANVIEN 

CREATE TABLE KHACHTHUE(
	MAKH VARCHAR(10),
	HoTen VARCHAR(20),
	LoaiKH CHAR(6),
	SoTienTichLuy MONEY
)

CREATE TABLE DATPHONG(
	MaPhong CHAR(5),
	MaKH VARCHAR(10),
	NgayDat DATE,
	GioThanhToan INT,
	SoGio INT,
	MaNV CHAR(4),
	CONSTRAINT DATPHONG_MaPhong_MAKH_NgayDat_PK PRIMARY KEY(MaPhong, MaKH, NgayDat),
)

CREATE TABLE PHONG(
	MaPhong CHAR(5) CONSTRAINT PHONG_MaPhong_PK PRIMARY KEY,
	TenPhong VARCHAR(20),
	LoaiPhong CHAR(8),
	GiaCoBan MONEY,
	MaKhu CHAR(8)
)

ALTER TABLE TRUC ADD		
	CONSTRAINT TRUC_MaNV_FK FOREIGN KEY(MaNV)
				REFERENCES NHANVIEN(MaNV)


ALTER TABLE TRUC ADD
	